kbcp:
  sci:
    6: 
       - rhyatt@kippchicago.org
       - lspears@kippchicago.org
       - esale@kippchicago.org
       - jcannon@kippchicago.org
       - chaid@kippchicago.org
    7: 
      - apaz@@kippchicago.org
      - esale@kippchicago.org
      - jcannon@kippchicago.org
      - chaid@kippchicago.org
  math:
    6: 
      - dwhitlock@kippchicago.org
      - lspears@kippchicago.org
      - esale@kippchicago.org
      - chaid@kippchicago.org
    7: 
      - aalbert@kippchicago.org
      - esale@kippchicago.org
      - jcannon@kippchicago.org
      - chaid@kippchicago.org
    
kas:
  sci:
    5: 
      - hhawkins@kippchicago.org
      - klee@kippchicago.org
      - jcannon@kippchicago.org
      - chaid@kippchicago.org
      - vpathiparampil@kippchicago.org
  math:
    5: 
      - wpaul@kippchicago.org
      - mfernelius@kippchicago.org
      - klee@kippchicago.org
      - chaid@kippchicago.org
      - vpathiparampil@kippchicago.org 
      