kbcp:
  sci:
    6: 
       - rhyatt@kippchicago.org
       - lspears@kippchicago.org
       - esale@kippchicago.org
       - jcannon@kippchicago.org
       - chaid@kippchicago.org
    7: 
      - apaz@@kippchicago.org
      - esale@kippchicago.org
      - jcannon@kippchicago.org
      - chaid@kippchicago.org
  math:
    6: 
      - dwhitlock@kippchicago.org
      - lspears@kippchicago.org
      - esale@kippchicago.org
      - chaid@kippchicago.org
    7: 
      - aalbert@kippchicago.org
      - esale@kippchicago.org
      - jcannon@kippchicago.org
      - chaid@kippchicago.org
  ela:
    6:
      - bbaker@kippchicago.org
      - lspears@kippchicago.org
      - esale@kippchicago.org
      - chaid@kippchicago.org
    7:
      - mrodriguez@kippchicago.org
      - esale@kippchicago.org
      - chaid@kippchicago.org
      
    
kas:
  sci:
    5: 
      - hhawkins@kippchicago.org
      - klee@kippchicago.org
      - jcannon@kippchicago.org
      - chaid@kippchicago.org
      - vpathiparampil@kippchicago.org
  math:
    5: 
      - wpaul@kippchicago.org
      - mfernelius@kippchicago.org
      - klee@kippchicago.org
      - chaid@kippchicago.org
      - vpathiparampil@kippchicago.org 
  ela:
    5: 
      - mkoler@kippchicago.org
      - vpathiparampil@kippchicago.org
      - klee@kippchicago.org
      - chaid@kippchicago.org

kams:
  sci:
    6: 
      - edelaney@kippchicago.org
      - lhenley@kippchicago.org
      - chaid@kippchicago.org
    7: 
      - mschwartz@kippchicago.org
      - edelaney@kippchicago.org
      - lhenley@kippchicago.org
      - chaid@kippchicago.org
  math:
    6: 
      - ekelp@kippchicago.org
      - jcannon@kippchicago.org
      - lhenley@kippchicago.org
      - chaid@kippchicago.org
    7: 
      - omcquade@kippchicago.org
      - jcannon@kippchicago.org
      - lhenley@kippchicago.org
      - chaid@kippchicago.org
    8:
      - mlaperuto@kippchicago.org
      - jcannon@kippchicago.org
      - lhenley@kippchicago.org
      - chaid@kippchicago.org
  ela:
    6:
      - jtheibert@kippchicago.org
      - lharrison@kippchicago.org
      - lhenley@kippchicago.org
      - chaid@kippchicago.org
    7:
      - lharrison@kippchicago.org
      - lhenley@kippchicago.org
      - chaid@kippchicago.org
    8:
      - ehawkins@kippchicago.org
      - lharrison@kippchicago.org
      - lhenley@kippchicago.org
      - chaid@kippchicago.org  